//! Generated by `scripts/npu/catalog.py` from `scripts/npu/out/bundles/manifest.json`; do not edit.
//! whisper-small @ 973afd24965f72e36ca33b3055d56a652f456b4d, LiteRT 2.2.0, QAIRT 2.47.0.260601.

use crate::model::Model;
use crate::npu::Bundle;

pub(crate) static BUNDLES: [Bundle; 7] = [
    Bundle { soc: "SM8450", htp: 69, files: &[
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8450-cross.tflite", file: "cross.tflite", bytes: 28730784, sha256: "fc460678a9d6a90c62b3dce438cf12c689424f07794fce0a51700bc7d2a185e1" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8450-decoder.tflite", file: "decoder.tflite", bytes: 359807344, sha256: "876f62563226353b5d1e9b7b9f86426351614a5975e5b30008b6bfbd5fc7550b" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8450-encoder.tflite", file: "encoder.tflite", bytes: 240821680, sha256: "3fa5c606a1d28ffb721b9822e9a217c363b5f4c0dad9b145b9079345f722c14d" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8450-generation_config.json", file: "generation_config.json", bytes: 3868, sha256: "71565b8ef50d0bf7a1193ed4bbed195b94e70c18894d81bba2f1233dcec3ab53" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8450-shapes.json", file: "shapes.json", bytes: 101, sha256: "a465579a06c71c73abb012960fef315f6eb8b9b7259f6dbe712b4cb506912d2e" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8450-tokenizer.json", file: "tokenizer.json", bytes: 2480466, sha256: "27fc476bfe7f17299480be2273fc0608e4d5a99aba2ab5dec5374b4482d1a566" },
    ] },
    Bundle { soc: "SM8475", htp: 69, files: &[
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8475-cross.tflite", file: "cross.tflite", bytes: 28730784, sha256: "36a56e5fe2926442f46d5aae2071252f4a6c3281b6606fdcac9dcb785a93f9f4" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8475-decoder.tflite", file: "decoder.tflite", bytes: 359807344, sha256: "4db9e113936d1a4de26728c5c6e76e8d655b3b9eb4d7e46378e27641f52f6039" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8475-encoder.tflite", file: "encoder.tflite", bytes: 240317872, sha256: "a0a0e5fb38f104f1fa160b0117fc3a539b97d37a127162193ffd10c5282cea11" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8475-generation_config.json", file: "generation_config.json", bytes: 3868, sha256: "71565b8ef50d0bf7a1193ed4bbed195b94e70c18894d81bba2f1233dcec3ab53" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8475-shapes.json", file: "shapes.json", bytes: 101, sha256: "a465579a06c71c73abb012960fef315f6eb8b9b7259f6dbe712b4cb506912d2e" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8475-tokenizer.json", file: "tokenizer.json", bytes: 2480466, sha256: "27fc476bfe7f17299480be2273fc0608e4d5a99aba2ab5dec5374b4482d1a566" },
    ] },
    Bundle { soc: "SM8550", htp: 73, files: &[
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8550-cross.tflite", file: "cross.tflite", bytes: 28775840, sha256: "f429d4ad31bbca0a2adab0559e5bda225f9eea286fe192999fcf08e957dacaa5" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8550-decoder.tflite", file: "decoder.tflite", bytes: 361789808, sha256: "04f5bac09e02315d108e241ab78705f824a4d8fef542d2e36ad50e643577ca67" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8550-encoder.tflite", file: "encoder.tflite", bytes: 242169264, sha256: "e2237f23d0b60522341d642c8e215c61a38bd4641f058eda70cd691ed53f9e11" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8550-generation_config.json", file: "generation_config.json", bytes: 3868, sha256: "71565b8ef50d0bf7a1193ed4bbed195b94e70c18894d81bba2f1233dcec3ab53" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8550-shapes.json", file: "shapes.json", bytes: 101, sha256: "a465579a06c71c73abb012960fef315f6eb8b9b7259f6dbe712b4cb506912d2e" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8550-tokenizer.json", file: "tokenizer.json", bytes: 2480466, sha256: "27fc476bfe7f17299480be2273fc0608e4d5a99aba2ab5dec5374b4482d1a566" },
    ] },
    Bundle { soc: "SM8650", htp: 75, files: &[
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8650-cross.tflite", file: "cross.tflite", bytes: 28743072, sha256: "5fb1f793e2a591ac9d7e2e9f0d7bf8ea5d26aebe8adc01fa54e587f53b2ae3c0" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8650-decoder.tflite", file: "decoder.tflite", bytes: 361789808, sha256: "b6558daf7dc144a7f63156aea86814449229b2edcd66e6241f48f1b3b81b25a8" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8650-encoder.tflite", file: "encoder.tflite", bytes: 241960368, sha256: "f0a45e93e741ebe67d76959a1f3876691fa8e0a675483dbf612c6fc8b49a4a27" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8650-generation_config.json", file: "generation_config.json", bytes: 3868, sha256: "71565b8ef50d0bf7a1193ed4bbed195b94e70c18894d81bba2f1233dcec3ab53" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8650-shapes.json", file: "shapes.json", bytes: 101, sha256: "a465579a06c71c73abb012960fef315f6eb8b9b7259f6dbe712b4cb506912d2e" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8650-tokenizer.json", file: "tokenizer.json", bytes: 2480466, sha256: "27fc476bfe7f17299480be2273fc0608e4d5a99aba2ab5dec5374b4482d1a566" },
    ] },
    Bundle { soc: "SM8750", htp: 79, files: &[
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8750-cross.tflite", file: "cross.tflite", bytes: 28829088, sha256: "4ea4aa84783eeccd3d621a9e990e491d0d258a3944f3904f5261ec023a97709d" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8750-decoder.tflite", file: "decoder.tflite", bytes: 361818480, sha256: "3e6070039068c0b9aa23c8cf4d6e91277b376f80b12baa24dc99b884e05beace" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8750-encoder.tflite", file: "encoder.tflite", bytes: 242349488, sha256: "b35a02d617223edd1d078f335570a47cdc81e6817122b98d139adb575d5a25c3" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8750-generation_config.json", file: "generation_config.json", bytes: 3868, sha256: "71565b8ef50d0bf7a1193ed4bbed195b94e70c18894d81bba2f1233dcec3ab53" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8750-shapes.json", file: "shapes.json", bytes: 101, sha256: "a465579a06c71c73abb012960fef315f6eb8b9b7259f6dbe712b4cb506912d2e" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8750-tokenizer.json", file: "tokenizer.json", bytes: 2480466, sha256: "27fc476bfe7f17299480be2273fc0608e4d5a99aba2ab5dec5374b4482d1a566" },
    ] },
    Bundle { soc: "SM8845", htp: 81, files: &[
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8845-cross.tflite", file: "cross.tflite", bytes: 28829088, sha256: "2585b48d088ae5649a543ee03289835c4663f3e0c9f3b6a29afcc509b43d3450" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8845-decoder.tflite", file: "decoder.tflite", bytes: 361818480, sha256: "42eeb0c8c3f27cb438dddf7b7a301fe73b59a1293e36b031f84b1b060c2e8739" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8845-encoder.tflite", file: "encoder.tflite", bytes: 241472944, sha256: "1977f1b358d12b439d6a6fe4e023fd56ef51c6ed5b01132b235d1924da45bbe7" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8845-generation_config.json", file: "generation_config.json", bytes: 3868, sha256: "71565b8ef50d0bf7a1193ed4bbed195b94e70c18894d81bba2f1233dcec3ab53" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8845-shapes.json", file: "shapes.json", bytes: 101, sha256: "a465579a06c71c73abb012960fef315f6eb8b9b7259f6dbe712b4cb506912d2e" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8845-tokenizer.json", file: "tokenizer.json", bytes: 2480466, sha256: "27fc476bfe7f17299480be2273fc0608e4d5a99aba2ab5dec5374b4482d1a566" },
    ] },
    Bundle { soc: "SM8850", htp: 81, files: &[
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8850-cross.tflite", file: "cross.tflite", bytes: 28951968, sha256: "9f54a03d880ebf9f8b5ce3183eae765bf126b73c207d347afa86dbec567ee043" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8850-decoder.tflite", file: "decoder.tflite", bytes: 361961840, sha256: "928753d372217d72854c004375f5657014a3e333f441385c2d131f0f2f9efb34" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8850-encoder.tflite", file: "encoder.tflite", bytes: 242537904, sha256: "1a38e5fe1375a287dd825a4c2a210e42af99e68e2974cd48a15e5455a4571f53" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8850-generation_config.json", file: "generation_config.json", bytes: 3868, sha256: "71565b8ef50d0bf7a1193ed4bbed195b94e70c18894d81bba2f1233dcec3ab53" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8850-shapes.json", file: "shapes.json", bytes: 101, sha256: "a465579a06c71c73abb012960fef315f6eb8b9b7259f6dbe712b4cb506912d2e" },
        Model { url: "https://github.com/attacca-cc/zyris/releases/download/npu-models-1/whisper-small-npu-SM8850-tokenizer.json", file: "tokenizer.json", bytes: 2480466, sha256: "27fc476bfe7f17299480be2273fc0608e4d5a99aba2ab5dec5374b4482d1a566" },
    ] },
];
