"""Write crates/zyris-voice/src/npu_catalog.rs from out/bundles/manifest.json.

Every bundle file as a `model::Model`: the release asset URL (each file names its release:
npu-models-1 for the first six, npu-models-2 for the ten-second set; the asset name carries the
SoC), its name on disk, its size and its SHA-256. The app checks every file against these before
it loads anything.
"""
import json, pathlib

BASE = "https://github.com/attacca-cc/zyris/releases/download"
HERE = pathlib.Path(__file__).parent
OUT = HERE / "../../crates/zyris-voice/src/npu_catalog.rs"

def main():
    manifest = json.loads((HERE / "out/bundles/manifest.json").read_text())
    lines = [
        "//! Generated by `scripts/npu/catalog.py` from `scripts/npu/out/bundles/manifest.json`; do not edit.",
        f"//! {manifest['model']} @ {manifest['revision']}, LiteRT {manifest['litert']}, QAIRT {manifest['qairt']}.",
        "",
        "use crate::model::Model;",
        "use crate::npu::Bundle;",
        "",
        f"pub(crate) static BUNDLES: [Bundle; {len(manifest['socs'])}] = [",
    ]
    for soc, entry in sorted(manifest["socs"].items()):
        lines.append(f'    Bundle {{ soc: "{soc}", htp: {entry["htp"]}, files: &[')
        for f in entry["files"]:
            url = f"{BASE}/{f.get('release', 'npu-models-1')}/whisper-small-npu-{soc}-{f['name']}"
            lines.append(f'        Model {{ url: "{url}", file: "{f["name"]}", bytes: {f["bytes"]}, sha256: "{f["sha256"]}" }},')
        lines.append("    ] },")
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{len(manifest['socs'])} bundles -> {OUT.resolve()}")

if __name__ == "__main__":
    main()
