fn main() {
    // Only the bench links LiteRT, and only for Android: the clip generator runs on the desktop.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("android") {
        return;
    }
    let sdk = std::env::var("LITERT_SDK").expect("run through android-env.sh");
    let headers = format!("{sdk}/litert_cc_sdk");
    // `build_config.h` is generated by LiteRT's CMake from a template; both flags off, as in the
    // released libLiteRt.so, which has GPU and NPU support.
    let out = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let config = out.join("include/litert/build_common");
    std::fs::create_dir_all(&config).unwrap();
    let template = std::fs::read_to_string(format!("{headers}/litert/build_common/build_config.h.in")).unwrap();
    let generated = template
        .replace("#cmakedefine01 LITERT_BUILD_CONFIG_DISABLE_GPU", "#define LITERT_BUILD_CONFIG_DISABLE_GPU 0")
        .replace("#cmakedefine01 LITERT_BUILD_CONFIG_DISABLE_NPU", "#define LITERT_BUILD_CONFIG_DISABLE_NPU 0");
    std::fs::write(config.join("build_config.h"), generated).unwrap();
    bindgen::Builder::default()
        .header(format!("{headers}/litert/c/litert_compiled_model.h"))
        .header(format!("{headers}/litert/c/litert_environment.h"))
        .header(format!("{headers}/litert/c/litert_model.h"))
        .header(format!("{headers}/litert/c/litert_options.h"))
        .header(format!("{headers}/litert/c/litert_tensor_buffer.h"))
        .clang_arg(format!("-I{}", out.join("include").display()))
        .clang_arg(format!("-I{headers}"))
        .allowlist_function("LiteRt.*")
        .allowlist_type("LiteRt.*")
        .allowlist_var("kLiteRt.*")
        .prepend_enum_name(false)
        .generate()
        .expect("LiteRT's C headers bind")
        .write_to_file(std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("litert.rs"))
        .unwrap();
    println!("cargo:rustc-link-search=native={sdk}/aar/jni/arm64-v8a");
    println!("cargo:rustc-link-lib=dylib=LiteRt");
}
